### ISSUE TITLE
Support TOML?

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-config#94]
I like [how it looks](https://toml.io/en/).

**Comment by Mechite** [comment]
I personally dislike TOML due to syntactical complexity WRT things like arrays (will always be a controversial opinion).
However, if you would undertake this I would imagine you would prefer not to have a dependency on a seperate parsing library.

In this case, I would take a look at [night-config](https://github.com/TheElectronWill/night-config) as they have their own parsing implementations and zero dependencies as a result, and it has worked fine for years already.

On the plus side, you can support formats like HOCON too if you like their parsing system, forking this parsing implementation would lead to a tiny file size increase for avaje-config as a whole while allowing more formats to be supported.

**Comment by SentryMan** [comment]
I was thinking more of creating a separate module for the different formats

**Comment by Mechite** [comment]
> I was thinking more of creating a separate module for the different formats

If this then perhaps also add support for users to create their own parsers.

Also, probably an implementation of dotenv would be simple and useful, considering [dotenv-java](https://github.com/cdimascio/dotenv-java/blob/master/src/main/java/io/github/cdimascio/dotenv/internal/DotenvParser.java) does it in one file, <100 LOC.

### proposed module structure?
im proposing here a LOT of formats, don't know if it fits the scope to support a lot of formats
- `avaje-config` - some kind of bundle that includes properties and yaml?

- `avaje-config-core` - common

- `avaje-config-toml`
- `avaje-config-hocon`
- `avaje-config-json` (with jsonb's simple inbuilt reader? i mean only a simple reading system is needed)
- `avaje-config-json5`
- `avaje-config-properties`
- `avaje-config-yaml`
- `avaje-config-xml` (key value with a root `<application>` element, using JAXP)
- `avaje-config-hcl` (familiar format for sysadmins or anybody who has used eg terraform, see [hcl4j](https://github.com/bertramdev/hcl4j/))
- `avaje-config-dhall` (this has been growing lately, would be the first good implementation, see [dhallj](https://github.com/travisbrown/dhallj))

**Comment by SentryMan** [comment]
That recent pr adds support for custom parsers

**Comment by SentryMan** [comment]
> im proposing here a LOT of formats, don't know if it fits the scope to support a lot of formats

it probably does, but you won't find me writing a parser for them unless somebody actually needs one

**Comment by SentryMan** [comment]
Don't feel like it anymore, though anyone interested is free to reopen and implement
